### ISSUE TITLE
See NO CHAT tab

### ISSUE THREAD

**Issue by rorfun** [uniteandconquer/SYNQ#1]
Version：v0.2.0 beta
Sees only Accounts, Watchlists and Settings tabs.
No where to find Chat tab and hence could not test the chat feature..

**Comment by uniteandconquer** [comment]
Hi rorfun,

You need to create a new account or import an existing account, once you've done that you'll see an 'account item' on your screen, by tapping the login icon (a door with an arrow) you'll login to that account, swipe the screen to the left or tap on the 'ACTIONS ' tab where you'll see all the available actions. 

One of those actions is Qchat (it's on the bottom left)
